[package]
name = "sitemap-generator-rs"
version = "0.1.0"
edition = "2021"
authors = ["ntalb <sntalbsen@gmail.com>"]

[[bin]]
name = "sitemap-gen"
path = "src/main.rs"

[dependencies]
async-std = "1"
chrono = "0"
clap = { version="4", features = ["derive", "env"]}
surf = "2"
select = "0"
